[DEFAULT]
RPC_URL = https://mainnet.helius-rpc.com/?api-key=f2ff4683-2727-4a42-91b7-2371e0bbe928
HELIUS_API_KEY = f2ff4683-2727-4a42-91b7-2371e0bbe928
PUMPFUN_API_URL = https://pumpportal.fun
MAIN_WALLET_SEED = helmet left myth enhance alter endorse behave minimum useful pass walnut define
NUM_SUB_WALLETS = 20
WEBSOCKET_URL = wss://pumpportal.fun/api/data
HELIUS_WEBSOCKET_URL = wss://mainnet.helius-rpc.com/?api-key=f2ff4683-2727-4a42-91b7-2371e0bbe928
SNIPER_FARMER_TIME_TO_SELL_MINUTES = 5

OUTPUT_FOLDER = output
LOG_FILE = infinityato.log

# Staggered Launch Parameters
STAGGER_DEFAULT_AMOUNT = 0.001
STAGGER_DEFAULT_SLIPPAGE = 10
STAGGER_DEFAULT_PRIORITY_FEE = 0.0001
STAGGER_DEFAULT_POOL = pump

# Default Transaction Parameters
DEFAULT_SLIPPAGE = 10
DEFAULT_PRIORITY_FEE = 0.0005
DEFAULT_POOL = pump
PUMP_FUN_PROGRAM_ID = 6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P